### ISSUE TITLE
ZV vizitka

### ISSUE THREAD

**Issue by IxAriela** [8venom8/PROJEKT-Vizitka#1]
Ahoj,

technicky je to v podstatě dobře, ale máš tam 2 větší chyby, které si prosím oprav, než ti to uznám (viz zaškrtávátka). Pak jsem tam našla spíš takové drobnosti, které se hodí vědět :)

- pokud nemá být žádný rámeček a nebyl nikde dřív nastavený (že bys to potřebovala přebít), tak tam nemusíš mít border vůbec nastaveno
- box sizing byl tady nastaven už na prvním řádku, v html (a pak následně jako inherit u všeho - to je ta hvězdička), tak to tam taky být nemusí

- [x] když si i lehce změníš šířku monitoru, tak už nepasuje fotka na roh, kde má být. Dej ten img do divu sekce a nastav, ať je ten div relativní. A samozřejmě pak musíš upravit souřadnice obrázku.
- [x] text v odstavcích nemá být tučně (to máš v html v napojení daného písma, je tam pouze 700, což je tučné, ty tam potřebuješ i 400 nebo 500

**Comment by 8venom8** [comment]
Ahoj:) děkuju za zpětnou vazbu. Upravila jsem box-sizing jak jsem ho měla 2x. Fotku jsem vložila do sekce a už mi neujíždí. A doufám, že písmo už je taky ok :)

**Comment by IxAriela** [comment]
Ahoj, lepší, ale dala jsi tu fotku position: relative, ale měla by být absolute, teď ti dělá zbytečně velkou mezeru nad nadpisem :)

Každopádně zapisuju, až si to přečteš, můžeš issue zavřít :)
